name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Setup SSH Debug
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "=== FILE EXISTS ==="
          ls -la ~/.ssh
          echo "=== FIRST LINE ==="
          head -n 1 ~/.ssh/id_ed25519
          ssh-keyscan -p 2222 -H 209.38.35.216 >> ~/.ssh/known_hosts

      - name: Test SSH
        run: |
          ssh -o StrictHostKeyChecking=no ahmed@209.38.35.216 "echo CONNECTED"

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ahmed@209.38.35.216 << EOF
            cd /var/www/shopping_project
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
          EOF
